name: Deploy to VPS (no-console)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            APP_DIR=/home/deploy/apps/innertrade-screener
            SCRIPT_PATH=/root/its_wipe_sync_run.sh

            echo "== sync deploy script =="
            if [ -d "$APP_DIR/.git" ]; then
              cd "$APP_DIR"
              git fetch --all --prune
              git reset --hard origin/main || true
              sudo install -m 755 scripts/its_wipe_sync_run.sh "$SCRIPT_PATH"
            else
              tmpdir=$(mktemp -d)
              git clone --depth 1 https://github.com/innertrade/innertrade-screener.git "$tmpdir"
              sudo install -m 755 "$tmpdir"/scripts/its_wipe_sync_run.sh "$SCRIPT_PATH"
              rm -rf "$tmpdir"
            fi

            echo "== wipe & redeploy =="
            sudo bash "$SCRIPT_PATH"

            echo "== tail logs =="
            sudo journalctl -u screener.service -n 20 --no-pager || true
            sudo journalctl -u push_signals.service -n 20 --no-pager || true
            sudo journalctl -u menu_bot.service -n 20 --no-pager || true
