name: Deploy screener

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'main.py'
      - 'push_signals.py'
      - 'menu_bot.py'
      - 'requirements.txt'
      - 'deploy/systemd/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload wipe & sync script
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "scripts/its_wipe_sync_run.sh"
          target: "/root"

      - name: Run wipe & sync
        uses: appleboy/ssh-action@v1.0.3
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          command_timeout: 45m
          envs: TELEGRAM_BOT_TOKEN,TELEGRAM_CHAT_ID
          script: |
            set -euo pipefail
            install -m 755 /root/scripts/its_wipe_sync_run.sh /root/its_wipe_sync_run.sh
            bash /root/its_wipe_sync_run.sh
