name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write SSH key from secret
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "$VPS_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

      - name: Add host key
        run: ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}

      - name: Test SSH connectivity
        run: ssh -vvv -i ~/.ssh/id_ed25519 "$VPS_USER@$VPS_HOST" 'echo OK && uname -a'
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}

      - name: Rsync code to VPS
        run: |
          rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" ./ "$VPS_USER@$VPS_HOST:$VPS_PATH/"
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PATH: ${{ secrets.VPS_PATH }}

      - name: Restart service and show logs
        run: |
          ssh -i ~/.ssh/id_ed25519 "$VPS_USER@$VPS_HOST" \
            'sudo systemctl restart push_signals.service && sleep 4 && sudo journalctl -u push_signals.service -n 80 --no-pager'
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
