name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install ssh-client & rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client rsync

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts
