- name: Provision app on VPS
  run: |
    set -euo pipefail

    APP=/home/deploy/apps/innertrade-screener

    # 1) Убедимся, что .env есть (если нет — создадим пустой и выставим права)
    if [ ! -f "$APP/.env" ]; then
      install -m 600 /dev/null "$APP/.env"
      chown deploy:deploy "$APP/.env"
    fi

    # 2) Проставляем/обновляем секреты в .env
    grep -q '^TELEGRAM_BOT_TOKEN=' "$APP/.env" || echo 'TELEGRAM_BOT_TOKEN=' >> "$APP/.env"
    grep -q '^TELEGRAM_CHAT_ID='   "$APP/.env" || echo 'TELEGRAM_CHAT_ID='   >> "$APP/.env"

    sed -i \
      -e "s|^TELEGRAM_BOT_TOKEN=.*|TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}|" \
      -e "s|^TELEGRAM_CHAT_ID=.*|TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}|" \
      "$APP/.env"

    # 3) Пересоздаём venv и ставим зависимости (+ certifi для фиксa TLS)
    python3 -m venv "$APP/.venv"
    "$APP/.venv/bin/pip" install -U pip wheel certifi
    "$APP/.venv/bin/pip" install -r "$APP/requirements.txt"

    # 4) Делаем стабильный путь к CA-бандлу (фикс TLS ошибок)
    CERT_FILE=$("$APP/.venv/bin/python" - <<'PY'
import certifi, sys
sys.stdout.write(certifi.where())
PY
)
    ln -sf "$CERT_FILE" "$APP/cacert.pem"

    # 5) Обновляем systemd units из репозитория
    install -m 644 "$APP/deploy/systemd/"*.service /etc/systemd/system/
    systemctl daemon-reload

    # 6) Включаем и рестартим сервисы
    systemctl enable --now screener.service push_signals.service menu_bot.service
    systemctl restart screener.service push_signals.service menu_bot.service
